# -*- coding: utf-8 -*-
"""Trabalho Poo

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15438rKbRI34b91iQZv5HxqAZKVveo6tf
"""

import datetime
import requests

class Tarefa:
    def __init__(self, descricao, data_hora):
        self.descricao = descricao
        self.data_hora = data_hora

    def executar(self):
        pass

class Lembrete(Tarefa):
    def executar(self):
        print(f"Lembrete: {self.descricao} - {self.data_hora}")

class InformacaoMeteorologica(Tarefa):
    def executar(self):
        # Simulação simples, você pode substituir isso por uma API real de meteorologia
        temperatura = 25
        condicao = "Ensolarado"
        print(f"Informação Meteorológica: {condicao}, {temperatura}°C - {self.data_hora}")

class Piada(Tarefa):
    def executar(self):
        # Aqui você poderia integrar uma API de piadas, mas para simplicidade, usaremos piadas estáticas
        piadas = [
            "Por que o programador nunca mente? Porque sempre diz 'Hello World!'",
            "Qual é o doce favorito do desenvolvedor? Byte de morango.",
            "O que o algoritmo tímido faz? Só ordena quando é pedido."
        ]
        print(f"Piada: {piadas[self.data_hora.hour % len(piadas)]}")

class AssistenteVirtual:
    def __init__(self):
        self.tarefas = []

    def adicionar_tarefa(self, tarefa):
        self.tarefas.append(tarefa)

    def executar_tarefas(self):
        for tarefa in self.tarefas:
            tarefa.executar()

# Exemplo de uso
if __name__ == "__main__":
    assistente = AssistenteVirtual()
    assistente1 = AssistenteVirtual()

    lembrete = Lembrete("Reunião importante", datetime.datetime(2023, 12, 1, 10, 0))
    info_meteorologica = InformacaoMeteorologica("Previsão do tempo", datetime.datetime(2023, 12, 1, 8, 0))
    piada = Piada("Contar uma piada", datetime.datetime.now())

    assistente.adicionar_tarefa(lembrete)
    assistente.adicionar_tarefa(info_meteorologica)
    assistente.adicionar_tarefa(piada)
    assistente.executar_tarefas()

    lembrete1 = Lembrete('Jogar Bola', datetime.datetime(2023, 10, 16, 20))
    info_meterologica1 = InformacaoMeteorologica('previsao do tempo ', datetime.datetime(2023, 12, 13, 10))
    piada1 = Piada('Piada da hora', datetime.datetime.now())

    assistente1.adicionar_tarefa(lembrete1)
    assistente1.adicionar_tarefa(info_meterologica1)
    assistente1.adicionar_tarefa(piada1)

    assistente1.executar_tarefas()